listener {
  timeout = 60
  on-timeout = brightnessctl -s s 10% 
  on-resume = brightnessctl -r
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ monitor = "eDP-1", action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ monitor = "eDP-1", action = "enable" })' && brightnessctl -r
}

# vim: et sw=2 ts=2
