#!/usr/bin/env bash

# Provide a function that can inject nvm into a running shell session, this way
# I don't have to put up with having all of nvm injected into every zsh session
# and can only load it when I need to use it.

init_nvm() {
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/etc/bash_completion.d/nvm" ] && source "$NVM_DIR/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
}
