#!/usr/bin/env bash

# Provide a function that can inject nvm into a running shell session, this way
# I don't have to put up with having all of nvm injected into every zsh session
# and can only load it when I need to use it.

# TODO this is currently specialized to the hell that is homebrew on the Darwin family of OSes
# this is because I don't use nvm on personal machines
init_nvm() {
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
    [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
}
