#!/usr/bin/env zsh

export PATH="/home/echo/.pyenv/shims:${PATH}"
export PYENV_SHELL=zsh

init_pyenv() {
    command pyenv rehash 2>/dev/null
    pyenv() {
      local command=${1:-}
      [ "$#" -gt 0 ] && shift
      case "$command" in
      activate|deactivate|rehash|shell)
        eval "$(pyenv "sh-$command" "$@")"
        ;;
      *)
        command pyenv "$command" "$@"
        ;;
      esac
    }
}
