#!/usr/bin/env bash

# Provide an initializer for sdkman rather than having it bully its way into
# every zsh session.

sdkman-init() {
    export SDKMAN_DIR="$HOME/.sdkman"
    [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
}
