#!/usr/bin/env zsh

stardate() {
    local seconds_since_jan=$(( $(date -u +%j) * 86400 + $(date -u +%H) * 3600 + $(date -u +%M) * 60 + $(date -u +%S) ))
    local scaling_factor=31535.0
    local lower=$(printf "%08.4f" $(( $seconds_since_jan / $scaling_factor )) )
    echo $(date -u '+%y')$lower
}

# vim: set ft=sh:
