# Login shells


if [[ "$OSTYPE" != "darwin"* ]]; then
    export QT_QPA_PLATFORM=wayland
else
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
if [[ $(command -v zoxide) ]]; then
    eval "$(zoxide init zsh)"
fi

# vim: ft=zsh
