# Always runs
export LC_COLLATE=C
export _JAVA_AWT_WM_NONREPARENTING=1
export XZ_OPTS="--threads=0"
export XDG_CONFIG_HOME=$HOME/.config

if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi
