# The following lines were added by compinstall

zstyle ':completion:*' menu select
zstyle ':completion:*' rehash yes
zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _list _expand _complete _ignored _match _approximate _prefix
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' max-errors 1 numeric
zstyle ':completion:*' original true
zstyle ':completion:*' word true
zstyle :compinstall filename '/home/lcarsos/.zshrc'

autoload -Uz compinit
compinit

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd histignoredups
setopt nocaseglob extendedglob numericglobsort
setopt braceccl
setopt autolist automenu
setopt complete_in_word
unsetopt beep nomatch
bindkey -e
# End of lines configured by zsh-newuser-install

export EDITOR=vim
export TERMINAL=urxvtc
